### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by gitbreaker222** [ashwamegh/riot-webpack-starter#1]
# Environment infos

`node -v` -> v10.14.2
`npm -v` -> 6.4.1
OS: Ubuntu 18.04 LTS

# What I did

I tried to start the dev-server by doing:
```
npm i
npm start
```

can you reproduce this?

# What I get

Here is the complete log, where I also used `npm audit fix`. After that I could reproduce without the audit fix though

```
potatoUser@potatoComputer riot-webpack-starter-master $ npm i
npm WARN riot-plus-webpack@1.0.0 No repository field.

added 992 packages from 529 contributors and audited 15563 packages in 22.575s
found 32 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
  
potatoUser@potatoComputer riot-webpack-starter-master $ npm audit fix
npm WARN riot-plus-webpack@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@4.28.0
updated 2 packages in 13.277s
fixed 26 of 32 vulnerabilities in 15563 scanned packages
  1 package update for 6 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

potatoUser@potatoComputer riot-webpack-starter-master $ npm start

> riot-plus-webpack@1.0.0 start /path/to/Repos/riot-webpack-starter-master
> webpack-dev-server --inline --watch --hot --colors -d --port 3000

/path/to/Repos/riot-webpack-starter-master/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/path/to/Repos/riot-webpack-starter-master/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/path/to/Repos/riot-webpack-starter-master/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-plus-webpack@1.0.0 start: `webpack-dev-server --inline --watch --hot --colors -d --port 3000`
npm ERR! Exit status 1
```

**Comment by gitbreaker222** [comment]
ok I could get it running by reinstalling the latest version of `webpack-cli`
This is the answer on so that helped me figure it out: https://stackoverflow.com/a/52795175/3313410
This is now my dependency list:
```
{
  "name": "riot-plus-webpack",
  ...
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-preset-es2015-riot": "^1.1.0",
    "riot-hot-reload": "^1.0.0",
    "riot-tag-loader": "^2.0.2",
    "webpack": "^4.28.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.0"
  },
  "dependencies": {
    "riot": "^3.9.0"
  }
}
```
